import Head from "next/head";
import Image from "next/image";
import Layout from "@/components/Layout";
import Link from "next/link";
import { useEffect, useState } from "react";
import axios from "axios";
import { Slide } from "react-slideshow-image";
import AOS from 'aos';
import 'aos/dist/aos.css';
// import Card from '@mui/material/Card';
// import CardActions from '@mui/material/CardActions';
// import CardContent from '@mui/material/CardContent';
// import CardMedia from '@mui/material/CardMedia';
// import Button from '@mui/material/Button';
// import Typography from '@mui/material/Typography';
import "react-slideshow-image/dist/styles.css";
import { blue } from "@mui/material/colors";
const spanStyle = {
  padding: "20px",
  background: "#efefef",
  color: "#000000",
};

const divStyle = {
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  backgroundSize: "cover",
  height: "100vh",
  width: "100%",
};

const slideImages = [
  {
    url: "https://media.istockphoto.com/id/1316145932/photo/table-top-view-of-spicy-food.jpg?s=170667a&w=0&k=20&c=fx-caeGfzahlZarBeZ_3Jl43xO85t2cs3dmIS4b4FL0=",
  },
  {
    url: "https://wallpapercave.com/wp/wp1874166.jpg",
  },
  {
    url: "https://academy.getbackbar.com/hs-fs/hubfs/adult-bar-beautiful-1537635.jpg?width=600&name=adult-bar-beautiful-1537635.jpg",
  },
];

export default function Home() {

  useEffect(() => {
    AOS.init({ duration: 1000 });
  }, []);
  const [specialMenu, setSpecialMenu] = useState([]);
  const loadData = async () => {
    try {
      const res = await axios.get("/api/product");
      if (res.status===200) {
        
        setSpecialMenu(res.data);
      }
    } catch (error) {
      console.log(error);
    }
  };

  //Counter for Count 
  const counter = {
    activeUser: "50",
    totalUser: "1",
    toalMenu: "20",
    toalOrder: "300"
  }



  useEffect(() => {
    loadData();

  }, []);

  return (
    <>
      <Head>
        <title>Restaurent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* <div className="text-wraper scrolling-text">
          <h4>Please Visit Again</h4>
          <h4>Please Visit Again</h4>
          <h4>Please Visit Again</h4>
          <h4>Please Visit Again</h4>
        </div> */}
        {/* <div className="marques">
          <marquee bgcolor=" #0066ff">
            <h2 className="text-white">Please Visit Again</h2>
          </marquee>
        </div> */}
        <div className="slide-container">
          <Slide>
            {slideImages.map((slideImage, index) => (
              <div key={index}>
                <div
                  style={{
                    ...divStyle,
                    backgroundImage: `url(${slideImage.url})`,
                  }}
                ></div>
              </div>
            ))}
          </Slide>
        </div>
        {/* Offer div  */}
        {/* <div className="background_home">
          <div className="left">
            <h1>Enjoy Your Healthy Deliious food</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae reprehenderit, aperiam explicabo voluptate sint dolores eveniet omnis atque autem ex.</p>
          </div>
          <div className="right">
            <div className="image">
              <img src="https://www.freeiconspng.com/thumbs/fast-food-png/fast-food-png-most-popular-fast-food-snacks-in-your-area-and-most--3.png" alt="" />
            </div>
          </div>
        </div> */}
        <div className="offer">
          <div className="row_offer ">
            <div className="offer_col ">
              <div className="offer_flex">
                <div className="offer_left">
                  <img src="https://pngimg.com/d/shawarma_PNG37.png" alt="" />
                </div>
                <div className="offer_right">
                  <p>Today special</p>
                  <h3>22%off</h3>
                  <button className="btn allbtn">Add Cart</button>
                </div>
              </div>
            </div>
            <div className="offer_col ">
              <div className="offer_flex">
                <div className="offer_left">
                  <img src="https://www.pngitem.com/pimgs/m/193-1931894_sunil-momos-png-download-momos-png-transparent-png.png" alt="" />
                </div>
                <div className="offer_right">
                  <p>Friday special</p>
                  <h3>20%off</h3>
                  <button className="btn allbtn">Add Cart</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* About page */}
        <div className="specialitemsbox">
          <div className="text-center">
            <p className="titlename  dancing"> Exploer</p>
            <h1 className="title_name"> Our Special Menu</h1>
          </div>

          <div className="specialIemrow">
            {specialMenu && specialMenu.filter((i) => i.special === 'special_menu').map((item, index) => {
              return (
                <div data-aos="zoom-in-up" className="specail_col" key={index}>
                  <div className="special_item">
                    <div className="image">
                      <img
                        src={`/images/${item.image}`}
                        alt={item.description}
                      />
                    </div>
                    <div className=" d-flex justify-content-around">
                      <p className="fs-3">{item.name}</p>

                      <p className="font_bold">

                        <Link href={`/Menu?category=${encodeURIComponent(item.category)}`}>
                          {" "}
                          <i className="bi bi-arrow-right-short"></i>
                        </Link>
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>

          {/* <div className="items">
            <div className="rowsItems">
              {specialMenu.map((item, index) => {
                return (
                  <div className="cols">
                    <div className="card boxshdow">
                      <div className="image">
                        <img
                          src={`/uploads/${item.image}`}
                          className="card-img-top"
                          alt={item.description}
                        />
                      </div>

                      <div className="card-body">
                        <div className="d-flex justify-content-between">
                          <p>{item.name}</p>
                          <p>
                            <Link href="/">link</Link>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div> */}
        </div>


        <div className="whatyouget m-4">
          <div className="text-center my-5">
            <p className="titlename dancing">Services</p>
            <h1 className="titletitle title_name">What You Get</h1>
          </div>
          <div className="serviceflex">
            <div data-aos="zoom-in-left" className="cols  ">
              <div className="data iconservices">
                <i className="bi bi-bank text-success"></i>
                <h1 className="title_name">Online Payment</h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et
                  exercitationem recusandae corrupti alias obcaecati nulla eum
                  quae labore dicta deleniti!
                </p>
              </div>
            </div>
            <div className="cols  ">
              <div data-aos="zoom-out" className="data">
                <i className="bi bi-cart-dash-fill text-danger"></i>
                <h1 className="title_name">Quality Chef's</h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et
                  exercitationem recusandae corrupti alias obcaecati nulla eum
                  quae labore dicta deleniti!
                </p>
              </div>
            </div>
            <div className="cols  ">
              <div data-aos="zoom-out" className="data">
                <i className="bi bi-house-down-fill text-primary"></i>
                <h1 className="title_name">Home delivery</h1>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et
                  exercitationem recusandae corrupti alias obcaecati nulla eum
                  quae labore dicta deleniti!
                </p>
              </div>
            </div>
          </div>
        </div>
        {/* <div className="chef view  m-4">
          <div className="text-center my-5">
            <h1 className="titletitle dancing">Expert Chef</h1>
            <p className="titlename">Nibh purus integer elementum in. Tellus vulputate habitasse ut diam Auctor sit elementum, vulputate</p>
          </div>

          <div className="chef_row">

            <div className="card box_border">
              <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGh1bWFufGVufDB8fDB8fA%3D%3D&w=1000&q=80" className="card-img-top" alt="..." />
              <div className="card-body">
                <div className="links flex">
                  <li>  <Link href='/'><i className="bi bi-facebook"></i></Link></li>
                  <li><Link href='/'><i className="bi bi-instagram"></i></Link></li>
                  <li> <Link href='/'><i className="bi bi-twitter"></i></Link></li>
                </div>
              </div>
            </div>



            <div className="card box_border"  >
              <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGh1bWFufGVufDB8fDB8fA%3D%3D&w=1000&q=80" className="card-img-top" alt="..." />
              <div className="card-body">
                <div className="links flex">
                  <li>  <Link href='/'><i className="bi bi-facebook"></i></Link></li>
                  <li><Link href='/'><i className="bi bi-instagram"></i></Link></li>
                  <li> <Link href='/'><i className="bi bi-twitter"></i></Link></li>
                </div>
              </div>
            </div>


            <div className="card box_border" >
              <img src="https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGh1bWFufGVufDB8fDB8fA%3D%3D&w=1000&q=80" className="card-img-top" alt="..." />
              <div className="card-body">
                <div className="links flex">
                  <li>  <Link href='/'><i className="bi bi-facebook"></i></Link></li>
                  <li><Link href='/'><i className="bi bi-instagram"></i></Link></li>
                  <li> <Link href='/'><i className="bi bi-twitter"></i></Link></li>
                </div>
              </div>
            </div>
          </div>
        </div> */}
        {/* Show Active User and And All Menues in Number  */}
        <div className="chef view  m-4">
          <div className="text-center my-5">


          </div>
          <div className="show_users_row">
            <div data-aos="fade-up" className="show_users_col">
              <div className="icon">
                <i className="bi bi-person-check-fill"></i>
              </div>
              <div className="content">
                <h1>{counter.activeUser}K</h1>
                <p>Active Users</p>
              </div>
            </div>
            <div data-aos="fade-up" className="show_users_col">
              <div className="icon">
                <i className="bi bi-people-fill"></i>
              </div>
              <div className="content">
                <h1>{counter.totalUser}K</h1>
                <p>Total Users</p>
              </div>
            </div>
            <div data-aos="fade-up" className="show_users_col">
              <div className="icon">
                <i className="bi bi-menu-up"></i>
              </div>
              <div className="content">
                <h1>{counter.toalMenu}K</h1>
                <p>Total Menus</p>
              </div>
            </div>
            <div data-aos="fade-up" className="show_users_col">
              <div className="icon">
                <i className="bi bi-cart-fill"></i>
              </div>
              <div className="content">
                <h1>{counter.toalOrder}K</h1>
                <p>Total Order</p>
              </div>
            </div>
          </div>

        </div>
        <div className="download_mobile_app">
          <p className="downloadNow"> Download Now!</p>

          <h1>Download Our Mobile Application</h1>
          <p>Download Restaurant Mobile app for Android to manage easily in Online.</p>
          <div className="flex_two">
            <div className="play_store">
              <div className="image">
                <img src="https://www.freepnglogos.com/uploads/play-store-logo-png/play-store-logo-nisi-filters-australia-11.png" />

              </div>
            </div>
            <div className="app_store">

              <div className="image">
                <img src="https://w7.pngwing.com/pngs/270/658/png-transparent-app-store-apple-google-play-apple-text-logo-mobile-phones.png" />
              </div>

            </div>
          </div>
        </div>
      </Layout >
    </>
  );
}
